name: kswcardata
description: Interact with Mcu using AIDL on KSW-android car headunits.
version: 0.7.0
homepage: byme.dev/kswcardata

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.byme.kswcardata
        pluginClass: KswCarDataPlugin
