name: kswcardata
description: Interact with Mcu using AIDL on KSW-android car headunits.
version: 0.6.0
author: Jellepepe
homepage: byme.dev/kswcardata

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.byme.kswcardata
        pluginClass: KswCarDataPlugin
